// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALIfQUU4lMETXx0PblXQaILLHgPHiNn8',
    appId: '1:823612330924:web:4b538fb463c221b5c8e009',
    messagingSenderId: '823612330924',
    projectId: 'marquee-58316',
    authDomain: 'marquee-58316.firebaseapp.com',
    storageBucket: 'marquee-58316.appspot.com',
    measurementId: 'G-F4XFZMLSD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVprS7Sui6Sa-vpHuUpBPNYt89ZDaXRk',
    appId: '1:823612330924:android:1b507a2c5586d42cc8e009',
    messagingSenderId: '823612330924',
    projectId: 'marquee-58316',
    storageBucket: 'marquee-58316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJxejOWFYUELrTfVAmFT2qIUk2V9FR8k',
    appId: '1:823612330924:ios:b6aa0267c29758c2c8e009',
    messagingSenderId: '823612330924',
    projectId: 'marquee-58316',
    storageBucket: 'marquee-58316.appspot.com',
    iosClientId: '823612330924-b47g44132hvtn6p4v7e8575uuhku6r43.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManagement',
  );
}
